name: app-ci
on:
  push:
    branches: [main]
    paths: [app/**]
  pull_request:
    branches: [main]
    paths: [app/**]
jobs:
  build-ios:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.DIIG_REG_TOKEN }}
        clean: true
    - name: release_tesflight
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        API_KEY_H: ${{ secrets.API_KEY_H }}
        REFS_VERSION: ${{ github.ref }}
      run: |
        # select xcode 16 (self hosted)
        ls /Applications/
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

        # build and upload
        cd app
        pmtech/pmbuild ios
        echo "$API_KEY_H" >> code/api_key.h

        xcodebuild build -workspace build/ios/diig_ios.xcworkspace -configuration Release -scheme diig CODE_SIGNING_ALLOWED=NO
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.DIIG_REG_TOKEN }}
    - name: setup_jdk
      uses: actions/setup-java@v1
      with:
        java-version: 21.0
    - name: setup_gradle
      uses: gradle/actions/setup-gradle@v3
      with:
          gradle-version: 8.14.3
    - name: setup_env
      run: |
        echo $env:ANDROID_HOME
        echo $env:JAVA_HOME
        echo $env:PATH
        java -version
    - name: resolve_secrets
      run: |
        absPath=$(realpath app/dist/android/upload-keystore.jks)
        echo "ABS_KEYSTORE_PATH=$absPath" >> "$GITHUB_ENV"
        echo '${{secrets.ANDROID_API_KEY_H}}' >> app/code/api_key.h
    - name: build
      run: |
        cd app
        pmtech/pmbuild android
        cd build/android
        gradle wrapper
