name: debug-scrape
on:
  workflow_dispatch:
jobs:
  debug-scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install_deps
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade google-auth
        python3 -m pip install selenium
    - name: scrape_and_commit
      run: |
        cd scrape
        python3 dig.py -store phonica -key '${{secrets.SERVICE_ACCOUNT}}' -clear-trackers -verbose
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "- update phonica releases" || true
        git pull --rebase
        git push origin HEAD:mai
