name: release_tesflight
on:
  workflow_dispatch:
jobs:
  release_tesflight:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: update_tesflight
      run: |
        cd app
        pmtech/pmbuild ios -libs
        pmtech/pmbuild ios
        pmtech/pmbuild ios-testflight
