name: release
on:
  push:
    tags:
    - '*'
jobs:
  setup:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  release_tesflight:
    needs: setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: update_tesflight
      run: |
        cd app
        pmtech/pmbuild ios -libs
        pmtech/pmbuild ios
        pmtech/pmbuild ios-testflight
        xcrun altool --upload-app -f build/ios/export/diig.ipa -t ios -u ${{secrets.APP_EMAIL}} -p ${{secrets.APP_PASS}}
